### PR TITLE
Rails 5

### PR DESCRIPTION
**Pull request by gregmolnar**
Rails 5 is coming out soon, so we should run the test suite against master to see if there are any braking changes. So far it looks there wasn't any change which affects us.
Please don't merge this till Rails 5 is released. I will update the PR when the beta is out.

### CODE REVIEW

**Comment by andyklimczak** [comment]
I am working on a Rails 5.0.0.alpha project, and this gem does not work with it.

To test, I first included the gem in my gemfile (gem 'textacular'), then hopped in rails console and did a Model.basic_search('search term'). This gave back:
```
NameError: undefined local variable or method `scoped' for #<Class:0x005558150e76e0>
from /home/andy/.rubies/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-3a7609e2bafe/activerecord/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
```

I did the same steps in a Rails 4.2.4 project, and the gem spit back search results as expected for basic_search and advanced_search. So no problems there.

I'm double checking the gems in my rails 5 project to see if they are causing any conflicts.

**Comment by gregmolnar** [comment]
That issue is already fixed on my branch. @andyklimczak please include the rail5 branch in your gemfile:
```
gem 'textacular', github: 'gregmolnar/textacular', branch: 'ar5'
```
Please let me know if you have any issues with that. Rails5 beta is out soon and then I will merge this to master if there are no issues.

**Comment by andyklimczak** [comment]
I totally misunderstood which gem branch to use, my fault.

I tested basic_search, and advanced_search. Both worked as expected. Fuzzy_search and its similarity threshold is working. Limiting search columns by 'extend Searchable(:title)' worked.

I did not try any fancy multimodel search. 
So no issues on my end.

**Comment by gregmolnar** [comment]
@andyklimczak thanks for the feedback! I just realised since there is no backward compatibility issue, I will just merge this to master. So you can just include that in your project:
```gem 'textacular', github: 'textacular/textacular'```

**Comment by andyklimczak** [comment]
Awesome, thank you!

**Comment by ecin** [comment]
Thanks for keeping the gem up to date!

**Comment by olivierlacan** [comment]
@gregmolnar Could you cut a release for this change? The current latest version (3.2.2) doesn't seem to include it.

**Comment by gregmolnar** [comment]
@olivierlacan I released the new version.

**Comment by olivierlacan** [comment]
Thanks @gregmolnar! ❤️
